FROM golang:1.23 as builder

WORKDIR /app

COPY narrative/generation/go.mod .
COPY narrative/generation/go.sum .

RUN go mod download

COPY narrative/generation/pkg ./pkg

COPY narrative/generation/cmd ./cmd

RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd

#Start a new stage from scratch
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/server ./server

# Make the binary executable
RUN chmod +x ./server

EXPOSE 50052
