FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY datastore/ingestion/requirments.txt .
RUN pip install -r requirments.txt

COPY datastore/ingestion/src /app/src

ENV PYTHONPATH=/app
