FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get -y update; apt-get -y install curl

WORKDIR /app

ADD --chmod=755 https://astral.sh/uv/install.sh /install.sh
RUN /install.sh && rm /install.sh

COPY datastore/ingestion/requirments.txt .

RUN /root/.cargo/bin/uv pip install --system --no-cache -r requirments.txt

COPY datastore/ingestion/src /app/src
ENV PYTHONPATH=/app
