// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/prompt.proto

package prompt

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PromptService_GetNarrationPrompt_FullMethodName            = "/prompt.PromptService/GetNarrationPrompt"
	PromptService_GetSkillCheckResolutionPrompt_FullMethodName = "/prompt.PromptService/GetSkillCheckResolutionPrompt"
	PromptService_GetInsanityNarration_FullMethodName          = "/prompt.PromptService/GetInsanityNarration"
)

// PromptServiceClient is the client API for PromptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromptServiceClient interface {
	GetNarrationPrompt(ctx context.Context, in *GetNarrationPromptRequest, opts ...grpc.CallOption) (*Prompt, error)
	GetSkillCheckResolutionPrompt(ctx context.Context, in *GetSkillCheckResolutionPromptRequest, opts ...grpc.CallOption) (*Prompt, error)
	GetInsanityNarration(ctx context.Context, in *GetSanityNarrationRequest, opts ...grpc.CallOption) (*Prompt, error)
}

type promptServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromptServiceClient(cc grpc.ClientConnInterface) PromptServiceClient {
	return &promptServiceClient{cc}
}

func (c *promptServiceClient) GetNarrationPrompt(ctx context.Context, in *GetNarrationPromptRequest, opts ...grpc.CallOption) (*Prompt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Prompt)
	err := c.cc.Invoke(ctx, PromptService_GetNarrationPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promptServiceClient) GetSkillCheckResolutionPrompt(ctx context.Context, in *GetSkillCheckResolutionPromptRequest, opts ...grpc.CallOption) (*Prompt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Prompt)
	err := c.cc.Invoke(ctx, PromptService_GetSkillCheckResolutionPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promptServiceClient) GetInsanityNarration(ctx context.Context, in *GetSanityNarrationRequest, opts ...grpc.CallOption) (*Prompt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Prompt)
	err := c.cc.Invoke(ctx, PromptService_GetInsanityNarration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromptServiceServer is the server API for PromptService service.
// All implementations must embed UnimplementedPromptServiceServer
// for forward compatibility.
type PromptServiceServer interface {
	GetNarrationPrompt(context.Context, *GetNarrationPromptRequest) (*Prompt, error)
	GetSkillCheckResolutionPrompt(context.Context, *GetSkillCheckResolutionPromptRequest) (*Prompt, error)
	GetInsanityNarration(context.Context, *GetSanityNarrationRequest) (*Prompt, error)
	mustEmbedUnimplementedPromptServiceServer()
}

// UnimplementedPromptServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromptServiceServer struct{}

func (UnimplementedPromptServiceServer) GetNarrationPrompt(context.Context, *GetNarrationPromptRequest) (*Prompt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNarrationPrompt not implemented")
}
func (UnimplementedPromptServiceServer) GetSkillCheckResolutionPrompt(context.Context, *GetSkillCheckResolutionPromptRequest) (*Prompt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSkillCheckResolutionPrompt not implemented")
}
func (UnimplementedPromptServiceServer) GetInsanityNarration(context.Context, *GetSanityNarrationRequest) (*Prompt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInsanityNarration not implemented")
}
func (UnimplementedPromptServiceServer) mustEmbedUnimplementedPromptServiceServer() {}
func (UnimplementedPromptServiceServer) testEmbeddedByValue()                       {}

// UnsafePromptServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromptServiceServer will
// result in compilation errors.
type UnsafePromptServiceServer interface {
	mustEmbedUnimplementedPromptServiceServer()
}

func RegisterPromptServiceServer(s grpc.ServiceRegistrar, srv PromptServiceServer) {
	// If the following call pancis, it indicates UnimplementedPromptServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PromptService_ServiceDesc, srv)
}

func _PromptService_GetNarrationPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNarrationPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).GetNarrationPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_GetNarrationPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).GetNarrationPrompt(ctx, req.(*GetNarrationPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromptService_GetSkillCheckResolutionPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillCheckResolutionPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).GetSkillCheckResolutionPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_GetSkillCheckResolutionPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).GetSkillCheckResolutionPrompt(ctx, req.(*GetSkillCheckResolutionPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromptService_GetInsanityNarration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSanityNarrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromptServiceServer).GetInsanityNarration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromptService_GetInsanityNarration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromptServiceServer).GetInsanityNarration(ctx, req.(*GetSanityNarrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromptService_ServiceDesc is the grpc.ServiceDesc for PromptService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromptService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prompt.PromptService",
	HandlerType: (*PromptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNarrationPrompt",
			Handler:    _PromptService_GetNarrationPrompt_Handler,
		},
		{
			MethodName: "GetSkillCheckResolutionPrompt",
			Handler:    _PromptService_GetSkillCheckResolutionPrompt_Handler,
		},
		{
			MethodName: "GetInsanityNarration",
			Handler:    _PromptService_GetInsanityNarration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/prompt.proto",
}
