apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-embeddings-deployment
  labels:
    app: text-embeddings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-embeddings
  template:
    metadata:
      labels:
        app: text-embeddings
    spec:
      containers:
      - name: text-embeddings-container
        image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
        command:
          - text-embeddings-router
          - --model-id
          - jinaai/jina-embeddings-v2-base-en
          - --tokenization-workers
          - "4"
          - --port
          - "3000"
