apiVersion: apps/v1
kind: Deployment
metadata:
  name: narrative-prompt
  labels:
    app: narrative-prompt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: narrative-prompt
  template:
    metadata:
      labels:
        app: narrative-prompt
    spec:
      containers:
      - name: narrative-prompt
        image: narrative-prompt:latest
        command: ["./server"]
        env:
         - name: MAX_CONVESATION_HISTORY_TOKENS
           value: "80000"
