apiVersion: batch/v1
kind: Job
metadata:
  name: lore-initial-job
spec:
  template:
    spec:
      containers:
      - name: lore-initial-container
        image: datastore-ingestion:latest
        command: ["python", "src/job.py"]
        env:
         - name: LORE_ID
           value: "25ad5d9b-d233-4f97-afc7-6f62ab0cfb37"
         - name: DB_HOST
           value: "postgres"
         - name: DBNAME
           value: "lovecraft"
         - name: USER
           value: "lovecraft"
         - name: EMBEDDINGS_URL
           value: "http://text-embeddings-service:3000"
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      restartPolicy: OnFailure
  backoffLimit: 4
