apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.postgres.yaml
  - service.postgres.yaml
  - service.text-embeddings.yaml
  - deployment.text-embeddings.yaml
  - deployment.minio.yaml
  - job.migration_v1.yaml
  - job.lore_initial.yaml
