apiVersion: v1
kind: Service
metadata:
  name: text-embeddings-service
spec:
  selector:
    app: text-embeddings
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
