apiVersion: v1
kind: Service
metadata:
  name: narrative-generation
spec:
  selector:
    app: narrative-generation
  ports:
    - protocol: TCP
      port: 50002
      targetPort: 50002
  type: ClusterIP
