apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    system: lovecraft
    subsystem: datastore
    component: persistence
spec:
  selector:
    system: lovecraft
    subsystem: datastore
    component: persistence
  ports:
    - name: sql
      port: 5432
      targetPort: 5432
      protocol: TCP
