apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    component: persistence
    subsystem: datastore
    system: rollplaying
spec:
  selector:
    matchLabels:
      component: persistence
      subsystem: datastore
      system: roleplaying
  serviceName: postgres
  template:
    metadata:
      labels:
        component: persistence
        subsystem: datastore
        system: roleplaying
    spec:
      containers:
      - name: postgres
        image: pgvector/pgvector:pg16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: roleplaying
        - name: POSTGRES_PASSWORD
          value: supersecretpassword
        - name: POSTGRES_DB
          value: roleplaying
        volumeMounts:
        - name: pvc
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
